/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2019-10-03 13:59:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hw1003;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class input_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>BTS</title>\r\n");
      out.write("<link href=\"btslayout.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!--body-->\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--div wrap-->\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("  <!--div page_header-->\r\n");
      out.write("  <div id=\"page_header\">\r\n");
      out.write("  \t<!--logo image-->\r\n");
      out.write("    <div class=\"main_logo\"><a href=\"#\"><img src=\"images/main_logo.png\" width=\"200\" height=\"40\" /></a></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--div content1-->\r\n");
      out.write("  <div id=\"content1\">\r\n");
      out.write("  <form name=\"form1\" method=\"post\" action=\"output.jsp\">\r\n");
      out.write("  <table width=\"100%\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"25\" colspan=\"3\" bgcolor=\"#F8E9DC\"><blockquote>\r\n");
      out.write("      <p>* 이름</p>\r\n");
      out.write("    </blockquote></td>\r\n");
      out.write("    <td colspan=\"4\"><blockquote>\r\n");
      out.write("      <p>\r\n");
      out.write("        <input name=\"namefield\" type=\"text\" />\r\n");
      out.write("      </p>\r\n");
      out.write("    </blockquote></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"3\" bgcolor=\"#F8E9DC\"><blockquote>\r\n");
      out.write("      <p>* 성별</p>\r\n");
      out.write("    </blockquote></td>\r\n");
      out.write("    <td colspan=\"4\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("        <label>\r\n");
      out.write("              <input type=\"radio\" name=\"gender\" value=\"남성\" id=\"gender\" />\r\n");
      out.write("              남성\r\n");
      out.write("        </label>\r\n");
      out.write("        <label>\r\n");
      out.write("              <input type=\"radio\" name=\"gender\" value=\"여성\" id=\"gender\" />\r\n");
      out.write("              여성\r\n");
      out.write("        </label></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"3\" bgcolor=\"#F8E9DC\"><blockquote>\r\n");
      out.write("      <p>* 연령</p>\r\n");
      out.write("    </blockquote></td>\r\n");
      out.write("    <td colspan=\"4\"><blockquote>\r\n");
      out.write("      <p name=\"age\">\r\n");
      out.write("        <select name=\"age\">\r\n");
      out.write("          <option value=\"10대 미만\">10대 미만</option>\r\n");
      out.write("          <option value=\"10대\">10대</option>\r\n");
      out.write("          <option value=\"20대\">20대</option>\r\n");
      out.write("          <option value=\"30대\">30대</option>\r\n");
      out.write("          <option value=\"40대\">40대</option>\r\n");
      out.write("          <option value=\"50대\">50대</option>\r\n");
      out.write("          <option value=\"60대 이상\">60대 이상</option>\r\n");
      out.write("        </select>\r\n");
      out.write("      </p>\r\n");
      out.write("    </blockquote></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("  <tr bgcolor=\"#F8E9DC\">\r\n");
      out.write("    <td colspan=\"7\"><blockquote>\r\n");
      out.write("      <p>* 좋아하는 방탄소년단 멤버</p>\r\n");
      out.write("    </blockquote></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"80\">\r\n");
      out.write("      <label>\r\n");
      out.write("        <input type=\"checkbox\" name=\"lover\" value=\"슈가\" id=\"lover\" />\r\n");
      out.write("        슈가</label>\r\n");
      out.write("        <br /><div class=\"BTSimage\"><img src=\"images/sg.jpg\" width=\"60\" height=\"60\" /></div>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width=\"80\"><label><input type=\"checkbox\" name=\"lover\" value=\"뷔\" id=\"lover\" />\r\n");
      out.write("       뷔</label>\r\n");
      out.write("    \t<br /><div class=\"BTSimage\"><img src=\"images/vi.jpg\" width=\"60\" height=\"60\" /></div>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width=\"80\"><label>\r\n");
      out.write("        <input type=\"checkbox\" name=\"lover\" value=\"진\" id=\"lover\" />\r\n");
      out.write("        진</label>\r\n");
      out.write("        <br /><div class=\"BTSimage\"><img src=\"images/jin.jpg\" width=\"60\" height=\"60\" /></div>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width=\"80\"><label>\r\n");
      out.write("        <input type=\"checkbox\" name=\"lover\" value=\"RM\" id=\"lover\" />\r\n");
      out.write("        RM</label>\r\n");
      out.write("        <br /><div class=\"BTSimage\"><img src=\"images/rm.jpg\" width=\"60\" height=\"60\" /></div>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width=\"89\"><label>\r\n");
      out.write("        <input type=\"checkbox\" name=\"lover\" value=\"제이홉\" id=\"lover\" />\r\n");
      out.write("        제이홉</label>\r\n");
      out.write("        <br /><div class=\"BTSimage\"><img src=\"images/jh.jpg\" width=\"60\" height=\"60\" /></div>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width=\"71\"><label>\r\n");
      out.write("        <input type=\"checkbox\" name=\"lover\" value=\"지민\" id=\"lover\" />\r\n");
      out.write("        지민</label><br /><div class=\"BTSimage\"><img src=\"images/jm.jpg\" width=\"60\" height=\"60\" /></div>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width=\"81\"><label>\r\n");
      out.write("        <input type=\"checkbox\" name=\"lover\" value=\"정국\" id=\"lover\" />\r\n");
      out.write("        정국</label>\r\n");
      out.write("        <br /><div class=\"BTSimage\"><img src=\"images/jk.jpg\" width=\"60\" height=\"60\" /></div>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr bgcolor=\"#F8E9DC\">\r\n");
      out.write("    <td colspan=\"7\"><blockquote>\r\n");
      out.write("      <p>* 방탄소년단에게 전하는 응원의 글</p>\r\n");
      out.write("    </blockquote></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"7\"><blockquote>\r\n");
      out.write("      <p name=\"letter\" cols=\"80\" rows=\"10\">\r\n");
      out.write("        <textarea name=\"letter\" cols=\"80\" rows=\"10\"></textarea>\r\n");
      out.write("      </p>\r\n");
      out.write("    </blockquote></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"7\">\r\n");
      out.write("    <div class=\"sendimage\"><input type=\"image\" name=\"sendbtn\" id=\"sendbtn\" src=\"images/button.png\"></div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  </form></div></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
