/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2019-10-30 03:45:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.midtest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class input_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>교보문고 책 구매</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"layout.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function MM_preloadImages() { //v3.0\r\n");
      out.write("  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();\r\n");
      out.write("    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)\r\n");
      out.write("    if (a[i].indexOf(\"#\")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function MM_swapImgRestore() { //v3.0\r\n");
      out.write("  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function MM_findObj(n, d) { //v4.01\r\n");
      out.write("  var p,i,x;  if(!d) d=document; if((p=n.indexOf(\"?\"))>0&&parent.frames.length) {\r\n");
      out.write("    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}\r\n");
      out.write("  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];\r\n");
      out.write("  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);\r\n");
      out.write("  if(!x && d.getElementById) x=d.getElementById(n); return x;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function MM_swapImage() { //v3.0\r\n");
      out.write("  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)\r\n");
      out.write("   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function MM_openBrWindow(theURL,winName,features) { //v2.0\r\n");
      out.write("  window.open(theURL,winName,features);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\t<!-- header -->\r\n");
      out.write("  <div id=\"page_header\">\r\n");
      out.write("  <img src=\"images/kyobo_01.gif\" width=\"1240\" height=\"251\" /> </div>\r\n");
      out.write("  \t<!-- center -->\r\n");
      out.write("  <div id=\"page_center\">\r\n");
      out.write("  \t<!-- table -->\r\n");
      out.write("    <div class=\"table_layout\">\r\n");
      out.write("    <!-- form -->\r\n");
      out.write("    <form action=\"output.jsp\" method=\"post\">\r\n");
      out.write("      <table width=\"590px\" height=\"281px\" border=\"1\" cellspacing=\"1\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td class = \"menu\"><table width=\"590px\" height=\"281px\" border=\"1\" cellspacing=\"1\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"244\" class = \"menu\">도서명</td>\r\n");
      out.write("            <td width=\"337\" class = \"content\"><input name=\"bookTitle\" type=\"text\" id=\"bookTitle\" value=\"가을동화\" /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class = \"menu\">출판사</td>\r\n");
      out.write("            <td class = \"content\"><input name=\"bookCom\" type=\"text\" id=\"bookCom\" value=\"세종 출판사\" /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class = \"menu\">가격</td>\r\n");
      out.write("            <td class = \"content\"><p>\r\n");
      out.write("              <label>\r\n");
      out.write("                <input type=\"radio\" name=\"bookPrice\" value=\"10000원\" id=\"bookPrice_0\" />\r\n");
      out.write("                10000원</label>\r\n");
      out.write("              <label>\r\n");
      out.write("                <input name=\"bookPrice\" type=\"radio\" id=\"bookPrice_1\" value=\"15000원\" checked=\"checked\" />\r\n");
      out.write("                15000원</label>\r\n");
      out.write("              <label>\r\n");
      out.write("                <input type=\"radio\" name=\"bookPrice\" value=\"20000원\" id=\"bookPrice_2\" />\r\n");
      out.write("                20000원</label>\r\n");
      out.write("            </p></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class = \"menu\">분야</td>\r\n");
      out.write("            <td class = \"content\"><p>\r\n");
      out.write("              <label>\r\n");
      out.write("                <input name=\"bookJanre\" type=\"checkbox\" id=\"bookJanre_0\" value=\"여행\" checked=\"checked\" />\r\n");
      out.write("                여행</label>\r\n");
      out.write("              <label>\r\n");
      out.write("                <input type=\"checkbox\" name=\"bookJanre\" value=\"과학\" id=\"bookJanre_1\" />\r\n");
      out.write("                과학</label>\r\n");
      out.write("              <label>\r\n");
      out.write("                <input type=\"checkbox\" name=\"bookJanre\" value=\"예술\" id=\"bookJanre_2\" />\r\n");
      out.write("                예술</label>\r\n");
      out.write("              <label>\r\n");
      out.write("                <input type=\"checkbox\" name=\"bookJanre\" value=\"인테리어\" id=\"bookJanre_3\" />\r\n");
      out.write("                인테리어</label>\r\n");
      out.write("              <label>\r\n");
      out.write("                <input name=\"bookJanre\" type=\"checkbox\" id=\"bookJanre_4\" value=\"문학\" checked=\"checked\" />\r\n");
      out.write("                문학</label>\r\n");
      out.write("            </p></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class = \"menu\">구매일</td>\r\n");
      out.write("            <td class = \"content\"><select name=\"bookYear\" id=\"bookYear\">\r\n");
      out.write("      <option value=\"2016\">2016</option>\r\n");
      out.write("      <option value=\"2017\">2017</option>\r\n");
      out.write("      <option value=\"2018\">2018</option>\r\n");
      out.write("      <option value=\"2019\" selected=\"selected\">2019</option>\r\n");
      out.write("    </select>년\r\n");
      out.write("    <select name=\"bookMonth\">\r\n");
      out.write("      <option value=\"1\">1</option>\r\n");
      out.write("      <option value=\"2\">2</option>\r\n");
      out.write("      <option value=\"3\">3</option>\r\n");
      out.write("      <option value=\"4\">4</option>\r\n");
      out.write("      <option value=\"5\">5</option>\r\n");
      out.write("      <option value=\"6\">6</option>\r\n");
      out.write("      <option value=\"7\">7</option>\r\n");
      out.write("      <option value=\"8\">8</option>\r\n");
      out.write("      <option value=\"9\">9</option>\r\n");
      out.write("      <option value=\"10\" selected=\"selected\">10</option>\r\n");
      out.write("      <option value=\"11\">11</option>\r\n");
      out.write("      <option value=\"12\">12</option>\r\n");
      out.write("    </select>월\r\n");
      out.write("    <select name=\"bookDate\">\r\n");
      out.write("      <option value=\"1\">1</option>\r\n");
      out.write("      <option value=\"2\">2</option>\r\n");
      out.write("      <option value=\"3\">3</option>\r\n");
      out.write("      <option value=\"4\">4</option>\r\n");
      out.write("      <option value=\"5\">5</option>\r\n");
      out.write("      <option value=\"6\">6</option>\r\n");
      out.write("      <option value=\"7\">7</option>\r\n");
      out.write("      <option value=\"8\">8</option>\r\n");
      out.write("      <option value=\"9\">9</option>\r\n");
      out.write("      <option value=\"10\">10</option>\r\n");
      out.write("      <option value=\"11\">11</option>\r\n");
      out.write("      <option value=\"12\">12</option>\r\n");
      out.write("      <option value=\"13\">13</option>\r\n");
      out.write("      <option value=\"14\">14</option>\r\n");
      out.write("      <option value=\"15\">15</option>\r\n");
      out.write("      <option value=\"16\">16</option>\r\n");
      out.write("      <option value=\"17\">17</option>\r\n");
      out.write("      <option value=\"18\">18</option>\r\n");
      out.write("      <option value=\"19\">19</option>\r\n");
      out.write("      <option value=\"20\">20</option>\r\n");
      out.write("      <option value=\"21\">21</option>\r\n");
      out.write("      <option value=\"22\">22</option>\r\n");
      out.write("      <option value=\"23\">23</option>\r\n");
      out.write("      <option value=\"24\">24</option>\r\n");
      out.write("      <option value=\"25\">25</option>\r\n");
      out.write("      <option value=\"26\">26</option>\r\n");
      out.write("      <option value=\"27\">27</option>\r\n");
      out.write("      <option value=\"28\">28</option>\r\n");
      out.write("      <option value=\"29\">29</option>\r\n");
      out.write("      <option value=\"30\" selected=\"selected\">30</option>\r\n");
      out.write("      <option value=\"31\">31</option>\r\n");
      out.write("    </select>\r\n");
      out.write("    일</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td colspan=\"2\" class = \"order\"><input name=\"buy\" type=\"submit\" value=\"구매\" /><input name=\"cencle\" type=\"reset\" value=\"취소\" /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"main_banner\"><img src=\"images/kyobo_04.gif\" width=\"235\" height=\"370\" id=\"Image1\" onmouseover=\"MM_swapImage('Image1','','images/kyobo_04_1.gif',0)\" onmouseout=\"MM_swapImgRestore()\" /></div>\r\n");
      out.write("    <div class=\"main_banner1\"><img src=\"images/kyobo_05.gif\" width=\"120\" height=\"179\" /></div>\r\n");
      out.write("    <div class=\"main_banner2\"><img src=\"images/kyobo_08.png\" width=\"120\" height=\"183\" /></div>\r\n");
      out.write("    <div class=\"main_nav\"><img src=\"images/kyobo_14.png\" width=\"698\" height=\"41\" usemap=\"#Map\" border=\"0\" />\r\n");
      out.write("      <map name=\"Map\" id=\"Map\">\r\n");
      out.write("        <area shape=\"rect\" coords=\"99,0,198,38\" href=\"#\"onClick=\"MM_openBrWindow('popup.html','','width=225,height=225')\">\r\n");
      out.write("      </map>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- footer -->\r\n");
      out.write("  <div id=\"page_footer\"><img src=\"images/kyobo_10.gif\" width=\"1240\" height=\"207\" /></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
