/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2019-11-11 02:14:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.CHAPTER07;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import my.dao.*;
import my.util.*;
import my.model.*;
import java.util.*;
import java.sql.*;

public final class main1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/kimna/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/1111/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1492563438000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("my.model");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("my.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("my.dao");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- 프레픽스 c를 쓰겠다고 선언함 -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Div활용</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"design1.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#apDiv1 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 22px;\r\n");
      out.write("\ttop: 173px;\r\n");
      out.write("\twidth: 160px;\r\n");
      out.write("\theight: 180px;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("}\r\n");
      out.write("#apDiv2 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 176px;\r\n");
      out.write("\ttop: 155px;\r\n");
      out.write("\twidth: 250;\r\n");
      out.write("\theight: 250;\r\n");
      out.write("\tz-index: 2;\r\n");
      out.write("}\r\n");
      out.write("#apDiv3 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 781px;\r\n");
      out.write("\ttop: 176px;\r\n");
      out.write("\twidth: 210;\r\n");
      out.write("\theight: 230;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("}\r\n");
      out.write("#apDiv4 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 586px;\r\n");
      out.write("\ttop: 156px;\r\n");
      out.write("\twidth: 171px;\r\n");
      out.write("\theight: 213px;\r\n");
      out.write("\tz-index: 2;\r\n");
      out.write("}\r\n");
      out.write("#apDiv5 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 361px;\r\n");
      out.write("\ttop: 131px;\r\n");
      out.write("\twidth: 274px;\r\n");
      out.write("\theight: 267px;\r\n");
      out.write("\tz-index: 3;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"apDiv2\"></div>\r\n");
      out.write("<div id=\"apDiv3\"></div>\r\n");
      out.write("<div class=\"page_header\">\r\n");
      out.write("\t<div class=\"toplogo\"><img src=\"images/logo_top.jpg\" width=\"202\" height=\"28\" alt=\"designart\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"topmini\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li><a href=\"#\">FAVORITE </a></li>\r\n");
      out.write("        <li><a href=\"#\">LOGIN </a></li>\r\n");
      out.write("        <li><a href=\"#\">JOINUS </a></li>\r\n");
      out.write("        <li><a href=\"#\">CART</a></li>\r\n");
      out.write("        <li><a href=\"#\">ORDER</a></li>\r\n");
      out.write("        <li><a href=\"#\">MYPAGE</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<div class=\"topnav\">\r\n");
      out.write("\t  <ul><li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu01.jpg\"><img src=\"images/topmenu01_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu02.jpg\"><img src=\"images/topmenu02_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu03.jpg\"><img src=\"images/topmenu03_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu04.jpg\"><img src=\"images/topmenu04_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu05.jpg\"><img src=\"images/topmenu05_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu06.jpg\"><img src=\"images/topmenu06_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu07.jpg\"><img src=\"images/topmenu07_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu08.jpg\"><img src=\"images/topmenu08_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu09.jpg\"><img src=\"images/topmenu09_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu10.jpg\"><img src=\"images/topmenu10_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu11.jpg\"><img src=\"images/topmenu11_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu12.jpg\"><img src=\"images/topmenu12_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu13.jpg\"><img src=\"images/topmenu13_r.jpg\" class=\"over\"></a></li>\r\n");
      out.write("\t    <li><a href=\"#\" class=\"rollover\"><img src=\"images/topmenu14.jpg\"><img src=\"images/topmenu14_r.jpg\" class=\"over\"></a></li>      \r\n");
      out.write("      </ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <div class=\"topshadow\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("\t<div class=\"mainimg\">\r\n");
      out.write("\t  ");

	  			Connection conn = ConnectionProvider.getConnection();//1. 커넥션을 만ㄷ름
	  			List<Movie> movies = null;//4. 저장할 배열 선언하기
	  			try{//2. try catch문 만듦
	  				MovieDao dao = new MovieDao();//3. dao객체 생성
	  				movies = dao.selectList(conn);//4. movies에 저장
	  			}catch(SQLException e){}
	  
	  
      out.write("\r\n");
      out.write("\t  ");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /CHAPTER07/main1.jsp(104,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("list");
        // /CHAPTER07/main1.jsp(104,3) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(movies );
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write("<!-- el으로 movies를 list로 바꿔줌 -->\r\n");
      out.write("\t  ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("\t<div class=\"best\">\r\n");
      out.write("   \t  <div class=\"b_title\"></div>\r\n");
      out.write("        <div class=\"prolist\">\r\n");
      out.write("        \t<div class=\"prolist1\">\r\n");
      out.write("            \t<img src=\"images/pro1.jpg\" width=\"245\" height=\"260\" alt=\"심플미니귀걸이 목걸이Set\" />\r\n");
      out.write("                <p>심플미니귀걸이 목걸이Set</p>\r\n");
      out.write("                <p>골드[ac2675]</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        \t<div class=\"prolist2\">\r\n");
      out.write("            \t<img src=\"images/pro2.jpg\" width=\"245\" height=\"260\" alt=\"체인스퀘어 목걸이\" />\r\n");
      out.write("                <p>체인스퀘어 목걸이</p>\r\n");
      out.write("                <p>G-holic[ac2838]</p>\r\n");
      out.write("            </div>            \r\n");
      out.write("        \t<div class=\"prolist3\">\r\n");
      out.write("            \t<img src=\"images/pro3.jpg\" width=\"245\" height=\"260\" alt=\"드라마틱 목걸이\" />\r\n");
      out.write("                <p>심플미니귀걸이 목걸이Set</p>\r\n");
      out.write("                <p>G-holic[ac2838]</p>\r\n");
      out.write("            </div>   \r\n");
      out.write("        \t<div class=\"prolist4\">\r\n");
      out.write("            \t<img src=\"images/pro4.jpg\" width=\"245\" height=\"260\" alt=\"사각볼드 귀걸이\" />\r\n");
      out.write("                <p>사각볼드 귀걸이</p>\r\n");
      out.write("                <p>G-holic[ac2839]</p>\r\n");
      out.write("            </div>                     \r\n");
      out.write("        \t<div class=\"prolist5\">\r\n");
      out.write("            \t<img src=\"images/pro5.jpg\" width=\"245\" height=\"260\" alt=\"블랙 숄더백\" />\r\n");
      out.write("                <p>블랙 숄더백</p>\r\n");
      out.write("                <p>블랙[bag2005]</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"prolist6\">\r\n");
      out.write("            \t<img src=\"images/pro6.jpg\" width=\"245\" height=\"260\" alt=\"화이트체인 핸드백\" />\r\n");
      out.write("                <p>화이트체인 핸드백</p>\r\n");
      out.write("                <p>화이트[bag2012]</p>\r\n");
      out.write("            </div>            \r\n");
      out.write("        \t<div class=\"prolist7\">\r\n");
      out.write("            \t<img src=\"images/pro7.jpg\" width=\"245\" height=\"260\" alt=\"헐리우드 블랙 백팩\" />\r\n");
      out.write("                <p>헐리우드 블랙 백팩</p>\r\n");
      out.write("                <p>블랙[bag3978]</p>\r\n");
      out.write("            </div>   \r\n");
      out.write("        \t<div class=\"prolist8\">\r\n");
      out.write("            \t<img src=\"images/pro8.jpg\" width=\"245\" height=\"260\" alt=\"브라운 숄더백\" />\r\n");
      out.write("                <p>브라운 숄더백</p>\r\n");
      out.write("                <p>브라운[bag4578]</p>\r\n");
      out.write("            </div>              \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"callcenter\">\r\n");
      out.write("\t\t<div class=\"notice\">\r\n");
      out.write("\t\t  <ul>\r\n");
      out.write("\t\t    <li><a href=\"#\">[2012/12/25]사랑해요 고객님 이벤트에...</a></li>\r\n");
      out.write("            <li><a href=\"#\">[2012/12/25]신규회원 가입고객 이벤트 응모... </a></li>\r\n");
      out.write("            <li><a href=\"#\">[2012/12/25]후기를 남겨주시면 할인쿠폰...</a></li>\r\n");
      out.write("\t      </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        <div class=\"callban1\"><img src=\"images/csbanner.jpg\" alt=\"이용후기게시판, 질문대답,이용안내\" width=\"293\" height=\"91\" usemap=\"#Map\" border=\"0\" />\r\n");
      out.write("          <map name=\"Map\" id=\"Map\">\r\n");
      out.write("            <area shape=\"rect\" coords=\"8,7,89,88\" href=\"#\" />\r\n");
      out.write("            <area shape=\"rect\" coords=\"103,8,191,87\" href=\"#\" />\r\n");
      out.write("            <area shape=\"rect\" coords=\"202,10,287,87\" href=\"#\" />\r\n");
      out.write("          </map>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"callban2\"><img src=\"images/cscenter.jpg\" width=\"320\" height=\"91\" alt=\"고객센터 : 070-7945-7700\" />\r\n");
      out.write("        </div>    \t\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"page_footer\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"rootbtn\">\r\n");
      out.write("\t  <ul>\r\n");
      out.write("\t    <li><a href=\"#\">회사소개</a></li>\r\n");
      out.write("        <li><a href=\"#\">개인정보취급방침</a></li>\r\n");
      out.write("        <li><a href=\"#\">서비스이용약관</a></li>\r\n");
      out.write("        <li><a href=\"#\">이메일문의</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("    \r\n");
      out.write("\t<div class=\"copy\">\r\n");
      out.write("    \t<p>상호:(주)디자인아트 플러스. 대표:임화연. 주소:서울구로구 구로동 에이스 하이앤드타워2차.</p>\r\n");
      out.write("        <p>copyrights ⓒ 2000 designartplus allrights reserved.\r\n");
      out.write("        </p> \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /CHAPTER07/main1.jsp(105,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<!-- if로 테스트 부터 해주어야함 -->\r\n");
          out.write("\t  \t");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /CHAPTER07/main1.jsp(106,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("movie");
      // /CHAPTER07/main1.jsp(106,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/CHAPTER07/main1.jsp(106,4) '${list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t  \t\t\t  <div class=\"movie\"><img src = \"/1111/movies/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${movie.movieImage }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"/></div>\r\n");
            out.write("\t  \t\t\r\n");
            out.write("\t  \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
